// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © peterwayne3293

//@version=6
strategy("SPECIAL", overlay=true, fill_orders_on_standard_ohlc = true, initial_capital=10000)

// MACD
fastLength = input(12)
slowlength = input(26)
MACDLength = input(9)
MACD = ta.ema(close, fastLength) - ta.ema(close, slowlength)
aMACD = ta.ema(MACD, MACDLength)
delta = MACD - aMACD

// Technical Rating
res = input.timeframe("", title="Indicator Timeframe")
ratingSignal = input.string(defval = "All", title = "Rating is based on", options = ["MAs", "Oscillators", "All"])

import TradingView/TechnicalRating/3 as rating

StrongBound = 0.3
WeakBound = 0.1

getSignal(ratingTotal, ratingOther, ratingMA) =>
    if ratingSignal == "MAs"
        ratingMA
    else if ratingSignal == "Oscillators"
        ratingOther
    else
    	ratingTotal

[ratingTotal, ratingOther, ratingMA]  = request.security(syminfo.tickerid, res, rating.calcRatingAll())
tradeSignal = getSignal(ratingTotal, ratingOther, ratingMA)

dynSLpoints(factor) => factor * ta.atr(14) / syminfo.mintick


// EMA 200
len = input.int(200, minval=1, title="Length")
src = input(close, title="Source")
offset = input.int(title="Offset", defval=0, minval=-500, maxval=500, display = display.data_window)
out = ta.ema(src, len)
plot(out, title="EMA", color=color.blue, offset=offset)




// lazybear
lengthMA = input(34)
lengthSignal = input(9)
calc_smma(src, len) =>
    var float smma = na
    smma := na(smma) ? ta.sma(src, len) : (smma * (len - 1) + src) / len
    smma

calc_zlema(src, length) =>
    ema1 = ta.ema(src, length)
    ema2 = ta.ema(ema1, length)
    d = ema1 - ema2
    ema1 + d

src2 = hlc3
hi = calc_smma(high, lengthMA)
lo = calc_smma(low, lengthMA)
mi = calc_zlema(src2, lengthMA) 

md = (mi > hi) ? (mi - hi) : (mi < lo) ? (mi - lo) : 0
sb = ta.sma(md, lengthSignal)
sh = md - sb


if tradeSignal > StrongBound
    if (ta.crossover(sh, 0))
        // if MACD < 0 and aMACD < 0 
        if md < 0 and sb < 0 
            strategy.entry("long", strategy.long, comment="LONG!!")
if tradeSignal < -WeakBound
    if (ta.crossunder(sh, 0))
        strategy.entry("short", strategy.short, comment="SHORT")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)
strategy.exit("sl/tp", loss = dynSLpoints(3), trail_points = dynSLpoints(5), trail_offset = dynSLpoints(2))
